Wytn.Web/Models/ErrorViewModel.cs
namespace Wytn.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Wytn.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Wytn.Sys.Service.Interface;
using Wytn.Web.Models;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Wytn.Sys.Model.Entity;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Http;
using System;
using NPOI.XSSF.UserModel;
using System.IO;

namespace Wytn.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> logger;
        private readonly IConfiguration configuration;
        private readonly ICodeService codeService;

        public HomeController(ILogger<HomeController> logger, IConfiguration configuration, ICodeService codeService)
        {
            this.logger = logger;
            this.configuration = configuration;
            this.codeService = codeService;
        }

        public IActionResult Index()
        {
            ViewBag.Env = configuration["Env"];
            var list = codeService.findByCodePno("PROJECTS").OrderByDescending((c) => c.codePno)?.ToList();
            ViewBag.code = list;

            return View();
        }

        public IActionResult Privacy(string id)
        {
            if (id != null)
            {
                ViewBag.id = id;
            }
            return View();
        }
        [HttpPost]
        public IActionResult Import(IFormFile file)
        {
            try
            {
                if (file != null)
                {
                    //xlsx
                    XSSFWorkbook workbook;
                    XSSFSheet sheet;
                    using (var ms = new MemoryStream())
                    {
                        file.CopyTo(ms);
                        Stream stream = new MemoryStream(ms.ToArray());
                        workbook = new XSSFWorkbook(stream);
                    }
                    if (workbook != null)
                    {
                        //取得第一頁工作表 0:第一頁
                        sheet = (XSSFSheet)workbook.GetSheetAt(0);
                        //不需要被讀取的表頭行 0:第一行
                        int headerRow = 0;
                        //從第二行開始讀取 -> 最後一行
                        for (int i = (headerRow + 1); i <= sheet.LastRowNum; i++)
                        {
                            //讀取一整行
                            XSSFRow row = (XSSFRow)sheet.GetRow(i);
                            //一整行內從第一格開始讀起
                            for (int j=0; j < row.Cells.Count; j++)
                            {
                                //讀取該格內容
                                string cell = row.GetCell(j).ToString();
                            }
                        }
                    }

                }
            }
            catch (Exception e)
            {
                logger.LogError(e.Message);
            }

            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Wytn.Web/Controllers/ProjectController.cs
using System.Diagnostics;
using Wytn.Sys.Service.Interface;
using Wytn.Web.Models;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace Wytn.Web.Controllers
{
    public class ProjectController : Controller
    {
        private readonly ILogger<ProjectController> logger;
        private readonly IConfiguration configuration;
        private readonly ICodeService codeService;

        public ProjectController(ILogger<ProjectController> logger, IConfiguration configuration, ICodeService codeService)
        {
            this.logger = logger;
            this.configuration = configuration;
            this.codeService = codeService;
        }

        public IActionResult Index()
        {
            ViewBag.Env = configuration["Env"];

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Wytn.Web/Views/Home/Index.cshtml
@using Wytn.Sys.Model.Dto
@{
    ViewData["Title"] = "Home Page";

}

<div class="text-center">
    <h1 class="display-4">Welcome Environment:@ViewBag.Env </h1>

    @for (var i = 0;  i < @ViewBag.code.Count; i++)
    {
        var obj = @ViewBag.code[i];
        <label></label>
        <div class="card" style="width: 18rem;">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Card title @i</h5>
                <p class="card-text">@(obj?.codeName)</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>

            <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
        </div>
    }

Wytn.Web/Views/Project/Index.cshtml
@using Wytn.Sys.Model.Dto
@{
    ViewData["Title"] = "Home Page";

}

<div class="text-center">
    <h1 class="display-4">PROJECTS - Welcome Environment:@ViewBag.Env </h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Wytn.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Wytn.Web</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Wytn.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">PROJECTS</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Wytn.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>